### ISSUE TITLE
ApplicationBlueprinter pattern

### ISSUE THREAD

**Issue by toobulkeh** [procore/blueprinter#80] opened 2018-05-18 03:57 UTC
Is there any reason not to use the `Application` pattern with Blueprinter?

`application_blueprint.rb`:
```ruby
class ApplicationBlueprint < Blueprinter::Base
  identifier :id
end
```

`user_blueprint.rb`:
```ruby
class UserBlueprint < ApplicationBlueprint
  fields :name
end
```

**Comment by philipqnguyen** [comment] 2018-05-18 17:10
Definitely! There is no reason not to use the `ApplicationBlueprint` pattern. It is already a pattern that Procore is using internally as well and I highly recommend using that pattern in your projects.

**Comment by toobulkeh** [comment] 2018-05-18 20:47
Apparently extending a blueprint with an identifier removes it from the returned value. Is that expected?

IE, I had to add this line back to all of our blueprints:

```ruby
identifier :id
```

**Comment by philipqnguyen** [comment] 2018-05-22 21:28
I did a short test of your example locally and I can confirm you're correct and that it does not work. Will  have to look into it further.

**Comment by Systho** [comment] 2018-08-28 15:02
The problem is the view collection is a class instance variable, thus it's not the same in the parent class and in the subclass.

I've personally fixed the problem with this snippet in my BaseBlueprint

```
  class BaseBlueprint < Blueprinter::Base

    def self.inherited(sub_class)
      sub_class.identifier :id
    end

end
```

**Comment by philipqnguyen** [comment] 2018-08-28 17:05
@Systho you're right, class instance variable is the problem. I think you have the right solution.

**Comment by philipqnguyen** [comment] 2018-10-17 20:44
resolved by #105

**Closed by philipqnguyen** 2018-10-17 20:44 UTC
Labels: enhancement, good first PR, help wanted
